# .goreleaser.yaml
version: 2

project_name: gh-pwsh-skills

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: gh-pwsh-skills
    binary: gh-pwsh-skills
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=sup3r7-fabio

archives:
  - id: default
    builds:
      - gh-pwsh-skills
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 🚀 Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 🐛 Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 📚 Documentation
      regexp: '^.*?docs?(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 🔧 Other
      order: 999

release:
  github:
    owner: sup3r7-fabio
    name: gh-pwsh-skills
  name_template: "v{{ .Version }}"
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## PowerShell GitHub Skills CLI Extension {{ .Tag }}
    
    🚀 Interactive PowerShell GitHub Skills course assistant
    
    ### Installation
    ```bash
    gh extension install sup3r7-fabio/gh-pwsh-skills
    ```
    
    ### What's New
  footer: |
    ### Checksums
    
    The checksums are generated with sha256sum. You can verify the integrity of the downloaded files with:
    ```bash
    sha256sum -c checksums.txt
    ```
    
    **Full Changelog**: https://github.com/sup3r7-fabio/gh-pwsh-skills/compare/{{ .PreviousTag }}...{{ .Tag }}

# GitHub CLI extension specific settings
github_urls:
  api: https://api.github.com/
  upload: https://uploads.github.com/
  download: https://github.com/

# Disable Homebrew for now (can be enabled later)
brews: []

# Disable Docker for now (can be enabled later)  
dockers: []

# Custom publishers for GitHub CLI extensions
publishers:
  - name: github-cli-extension
    ids:
      - default
    cmd: |
      echo "GitHub CLI Extension published successfully!"
      echo "Install with: gh extension install sup3r7-fabio/gh-pwsh-skills"
